version: "3.8"

services:
  db:
    image: postgres:17.2
    container_name: my_db
    environment:
      POSTGRES_PASSWORD: my_password
      POSTGRES_USER: my_user
      POSTGRES_DB: money_flow
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - my_network
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - pg_data:/var/lib/postgresql/data
    
networks:
  my_network:
    name: my_network

volumes:
  pg_data: